### ISSUE TITLE
Data retrieval should continue if one program fails

### ISSUE THREAD

**Issue by jotaylor** [spacetelescope/cosmo#8]
Sometimes retrievals fail on the MAST side, the script should continue and remove those items from the queue
Traceback (most recent call last):
  File "/user/jotaylor/linux_anaconda3/envs/astroconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/user/jotaylor/linux_anaconda3/envs/astroconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/user/jotaylor/cos_monitoring/cos_monitoring/retrieval/find_new_cos_data.py", line 234, in <module>
    compare_tables(args.pkl_it)
  File "/user/jotaylor/cos_monitoring/cos_monitoring/retrieval/find_new_cos_data.py", line 214, in compare_tables
    print("Data missing for {0} programs".format(len(prop_keys)))
  File "cos_monitoring/retrieval/request_data.py", line 288, in run_all_retrievals
    all_tracking_ids = cycle_thru(prop_dict, prop, all_tracking_ids)
  File "cos_monitoring/retrieval/request_data.py", line 232, in cycle_thru
    ind_id = retrieve_data(prop_dir, prop_dict[prop])
  File "cos_monitoring/retrieval/request_data.py", line 162, in retrieve_data
    tmp_id = re.search("("+MYUSER+"[0-9]{5})", result).group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by jotaylor** [comment]
This was addressed with c27b52f62992572f859dd81870957dae195110cf by adding a try/except in retrieve_data function.
